import type { Metadata } from "next";
import { Inter, Rubik } from 'next/font/google'
import "./globals.css";

const inter = Inter({ subsets: ["latin"], weight: ['500', '600', '700', '800', '900'], variable: '--font-inter' })
const rubik = Rubik({ subsets: ["latin"], weight: ['500', '600', '700', '800', '900'], variable: '--font-rubik' })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${rubik.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
